export enum Subjects {
    AssignmentCreated = 'assignment:created',
    AssignmentUpdated = 'assignment:updated',
    LeiCreated = 'lei:created',
    LeiUpdated = 'lei:updated',
    UserCreated = 'user:created',
    UserUpdated = 'user:updated',
    UploadCreated = 'upload:created',
    NodeInitiate = 'node:initiate',
    NodeCreated = 'node:created',
    NodePayloadUpdated = 'node:payload-updated',
    NodeUpdated = 'node:updated',
    ProcessInitiate = 'process:initiate',
    ProcessCreated = 'process:created',
    ProcessPayloadUpdated = 'process:payload-updated',
    ProcessUpdated = 'process:updated',
    StageInitiate = 'stage:initiate',
    StageCreated = 'stage:created',
    StageUpdated = 'stage:updated',
    CaseCreated = 'case:created',
    CaseUpdated = 'case:updated',
    CaseNodeAction = 'case:node-action',
}